main:
	pdflatex dependency-graph.tex
	pdflatex dependency-graph.tex
	
	pdflatex exception_control_flow.tex
	pdflatex exception_control_flow.tex
	
	pdflatex handler_hello_world.tex
	pdflatex handler_hello_world.tex
	
	pdflatex impl-exception.tex
	pdflatex impl-exception.tex
	
	pdflatex impl-no-perform.tex
	pdflatex impl-no-perform.tex
	
	pdflatex impl-one-resume.tex
	pdflatex impl-one-resume.tex
	
	pdflatex impl-two-resume.tex
	pdflatex impl-two-resume.tex
	
	pdflatex naive.tex
	pdflatex naive.tex
	
	pdflatex secd.tex
	pdflatex secd.tex

